name: commerce_store
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  get: ^4.6.6
  logger: ^2.4.0
  get_storage: ^2.1.1
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  url_launcher: ^6.3.1
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.2
  lottie: ^3.1.3
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  google_sign_in: ^6.2.2
  connectivity_plus: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true



  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/animations/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/payment_methods/
    - assets/icons/categories/
    - assets/images/lottie_animation/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 800
          style: italic
